#!/bin/sh

# Script to finish debootstraping of base packages on first boot
# The script will move the real init at the correct place afterwards and exec it
# It will also properly install the kernel packages

set -x
export PATH="/sbin/:/usr/sbin/:/bin/:/usr/bin"
mount /proc/
mount -t sysfs sysfs /sys/
mount -a
mount -o remount,rw /
mount -o remount,rw /boot/
rm "$0"
mv "$0"_real "$0" # Dont move this after debootstrap, it will loop endlessly amongst other things.
/debootstrap/debootstrap --second-stage
dpkg -i /root/linux-*.deb
rm /root/linux-*.deb
sync
umount /boot
mount -o remount,ro /
exec "$0" "$@"
