#!/bin/sh -ex

tmp="$(mktemp -d)"
cleanup(){ cd /; rm -rf "$tmp"; }
trap cleanup EXIT TERM INT

cd "$tmp"

if apt-get download raspi-firmware
then
  dpkg-deb -xv raspi-firmware*.deb .
  cp ./lib/firmware/brcm/brcmfmac43455-sdio.txt /lib/firmware/brcm/brcmfmac43455-sdio.pine64,pinephone-pro.txt
else
  apt-get download linux-firmware-raspi2
  dpkg-deb -xv linux-firmware-raspi2*.deb .
  cp ./lib/firmware/brcm/brcmfmac43455-sdio.raspberrypi,400.txt /lib/firmware/brcm/brcmfmac43455-sdio.pine64,pinephone-pro.txt
fi
