#!/bin/sh

# If libgdk-pixbuf2.0-0 was installed, reinstall it. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=923289
if dpkg-query -W -f='${Status}\n' libgdk-pixbuf2.0-0 2>/dev/null | grep -q 'install ok installed'
then
  dpkg-reconfigure libgdk-pixbuf2.0-0
  update-mime-database /usr/share/mime
fi

# Make sure lightdm uses the the lightdm gtk greeter if installed
# In that greeter, selecting menu items on the touchscreen actually works, and there's an onscreen keyboard
update-alternatives --set lightdm-greeter /usr/share/xgreeters/lightdm-gtk-greeter.desktop

useradd --system -G pulse-access -d /usr/share/wys -s /usr/sbin/nologin wys
usermod -L wys

update-rc.d pulseaudio-enable-autospawn disable || true
update-rc.d pulseaudio defaults || true
update-rc.d pulseaudio enable || true
update-rc.d wys defaults || true
update-rc.d wys enable || true
systemctl disable pulseaudio-enable-autospawn.service || true
systemctl --user disable pulseaudio.service || true
systemctl enable pulseaudio-system.service || true
