#!/bin/sh -ex

if [ "$USE_IMAGE_BUILDER_REPO" = yes ] && [ -n "$IMAGE_BUILDER_REPO$IMAGE_BUILDER_REPO_KEY" ]
then
  apt-get update
  apt-get -y install ca-certificates wget gnupg2
  wget -O "/etc/apt/trusted.gpg.d/image-builder.asc" "$IMAGE_BUILDER_REPO_KEY"
  printf '%s' "$IMAGE_BUILDER_REPO" >>/usr/share/first-boot-setup/temporary-local-repo.list
  printf '%s' "$IMAGE_BUILDER_REPO" >/etc/apt/sources.list.d/image-builder.list
fi

update-rc.d volkeyttyswitcher defaults || true
update-rc.d volkeyttyswitcher enable || true
