#!/bin/sh

set -ex

vmlinuz="vmlinuz-$1"
dtb="linux-image-$1/$(cat $tmp/rootfs/etc/dtb_file)"

# Update /boot/zImage -> vmlinuz symlink
ln -sf "$vmlinuz" /boot/zImage

# Copy flat device tree binary
mkdir -p "/boot/$(dirname "$dtb")"
cp "/usr/lib/$dtb" "/boot/$dtb"

# Update flat device tree binary symlink
ln -sf "$dtb" /boot/devicetree
