#!/bin/sh

update-rc.d powerkey defaults
update-rc.d powerkey enable

useradd --system -G pulse-access -d /usr/share/wys wys

cat >>/etc/inittab <<EOF

# uart
T0:2345:respawn:/sbin/getty -L ttymxc0 115200 xterm

EOF
