#!/bin/sh
### BEGIN INIT INFO
# Provides:          modem
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Turn the modem on / off
# Description:       Turn the modem on / off
### END INIT INFO

do_start(){
  echo "Turning modem on..."
  echo 1 >/sys/class/modem-power/modem-power/device/powered_blocking
  do_status
}

do_stop(){
  echo "Turning modem off..."
  echo 0 >/sys/class/modem-power/modem-power/device/powered_blocking
  ! do_status
}

do_status(){
  if [ "$(cat /sys/class/modem-power/modem-power/device/powered)" = 1 ]
    then echo "Modem: ON"; return 0
    else echo "Modem: OFF"; return 1
  fi
}

do_"$1"
